#!/usr/bin/env bash
# Prints the Homebrew formula for release <version>, with the checksums from its SHA256SUMS:
#
#   scripts/release/homebrew-formula.sh <main|pinned> <version> <SHA256SUMS> [<url-base>]
#
#   main    Formula/jev.rb, class Jev. Refuses a pre-release version: the main formula only ever
#           points at a stable release.
#   pinned  Formula/jev@<version>.rb, class JevAT<digits>, keg-only, as the tap does for every tool.
#
# The formula installs the release archives for macOS and Linux on arm64 and x86_64 (the musl
# builds, so one binary runs on any Linux): the binary, the man pages and the bash, zsh and fish
# completions that every archive holds. Homebrew reads the version from the archive names, and
# `brew audit --strict` rejects a `version` line that repeats it. <url-base> is where the archives are downloaded from, by
# default the GitHub Release of v<version>; the release workflow's dry run points it at local
# files to install the formula for real before any release exists.
#
# A Homebrew install lives in the keg `<prefix>/Cellar/<formula>/<version>/`, next to Homebrew's
# INSTALL_RECEIPT.json. `jev update` relies on that layout to recognise a managed install, which
# never updates itself, so the binary must stay directly in the keg's bin/.
set -euo pipefail

if [ $# -lt 3 ] || [ $# -gt 4 ]; then
  echo "usage: $0 <main|pinned> <version> <SHA256SUMS> [<url-base>]" >&2
  exit 2
fi
kind=$1 version=$2 sums=$3
base=${4:-https://github.com/shaharia-lab/jev-cli/releases/download/v$version}

if ! grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$' <<< "$version"; then
  echo "error: '$version' is not a SemVer version" >&2
  exit 2
fi
case $kind in
  main)
    class=Jev keg_only=""
    case $version in *-*)
      echo "error: $version is a pre-release; the main formula only points at a stable release" >&2
      exit 1
      ;;
    esac
    ;;
  # Homebrew's class name for jev@1.2.3 drops everything that is not alphanumeric: JevAT123.
  pinned) class="JevAT${version//[^0-9A-Za-z]/}" keg_only=$'\n  keg_only :versioned_formula\n' ;;
  *)
    echo "error: the formula kind must be main or pinned, not '$kind'" >&2
    exit 2
    ;;
esac
[ -f "$sums" ] || { echo "error: $sums does not exist" >&2; exit 2; }

# The url and sha256 lines of one target's archive, as listed in SHA256SUMS.
archive() {
  local name="jev-$version-$1.tar.gz" sha
  sha=$(awk -v name="$name" '{ file = $2; sub(/^\*/, "", file) } file == name { print $1 }' "$sums")
  if ! grep -qE '^[0-9a-f]{64}$' <<< "$sha"; then
    echo "error: $sums has no checksum for $name" >&2
    return 1
  fi
  printf '      url "%s/%s"\n      sha256 "%s"' "$base" "$name" "$sha"
}
macos_arm=$(archive aarch64-apple-darwin)
macos_intel=$(archive x86_64-apple-darwin)
linux_arm=$(archive aarch64-unknown-linux-musl)
linux_intel=$(archive x86_64-unknown-linux-musl)

cat << EOF
# typed: false
# frozen_string_literal: true

# Generated by the release workflow of https://github.com/shaharia-lab/jev-cli; do not edit.
class $class < Formula
  desc "Unofficial CLI for TypeSafe AI's Jev model, for humans, scripts and AI agents"
  homepage "https://github.com/shaharia-lab/jev-cli"
  license any_of: ["MIT", "Apache-2.0"]
$keg_only
  on_macos do
    on_arm do
$macos_arm
    end
    on_intel do
$macos_intel
    end
  end

  on_linux do
    on_arm do
$linux_arm
    end
    on_intel do
$linux_intel
    end
  end

  def install
    bin.install "jev"
    man1.install Dir["man/man1/*.1"]
    bash_completion.install "completions/jev.bash" => "jev"
    zsh_completion.install "completions/_jev"
    fish_completion.install "completions/jev.fish"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/jev version --field version").strip
  end
end
EOF
